### ISSUE TITLE
Multiple Issues with StudySession Class

### ISSUE THREAD

**Issue by OKok-3** [CSC207-UofT/plannr#1]
I don't know if the implementation for study session is finished or not, if it's still in development sry in advance!

Implementation of StudySession class has multiple issues:
- No import for ArrayList
- Wrong name for the class constructor
- Missing the closing bracket "}" for the constructor method
- All getter methods are not using the "this" keyword to get the class instance variables, the code currently tries to get something that doesn't exist
- StudySession also does not extend the Event class

**Comment by cdw18** [comment]
Took care of the issues while implementing study session
