### ISSUE TITLE
Database Helper Methods Possibly In the Wrong Place

### ISSUE THREAD

**Issue by OKok-3** [CSC207-UofT/plannr#52]
I just noticed that the methods for storing and getting user's information is defined in `SignUpActivity.java` rather than `DatabaseHelper.java` and they are all private methods. Should we move them to `DatabaseHelper.java` instead since other pages may need to access those methods, like settings page?

**Comment by sarihammad** [comment]
Made a pull request that should deal with this issue. After it's approved, I will remove the methods from SignUpActivity.java and fix any other issues.
